# Generated by Django 2.0.dev20170604010711 on 2017-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0010_auto_20170616_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_commentary_1_description',
            new_name='product_all_color_hexa_code',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_commentary_2_description',
            new_name='product_all_color_name',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_commentary_3_description',
            new_name='product_all_size_info',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='product_commentary_1_image',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='product_commentary_2_image',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='product_commentary_3_image',
        ),
        migrations.AddField(
            model_name='productmaster',
            name='country',
            field=models.CharField(default='JP', max_length=100),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='product_commentary_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='product_commentary_image',
            field=models.TextField(null=True),
        ),
    ]
