# Generated by Django 2.0.dev20170604010711 on 2017-06-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0016_productmaster_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='model_id',
        ),
    ]
