# Generated by Django 2.0.dev20170604010711 on 2017-06-12 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_type', models.SmallIntegerField(choices=[(1, 'Product'), (2, 'Category')], db_index=True, default=1)),
                ('header_name', models.CharField(default='', max_length=50)),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RelatedProduct_product_id', to='demandware.ProductMaster'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
