# Generated by Django 2.0.dev20170604010711 on 2017-06-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0002_auto_20170613_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productmeta',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='relatedproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='relatedproduct',
            old_name='related_product_id',
            new_name='related_product',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='productmeta',
            unique_together={('product', 'key')},
        ),
    ]
