# Generated by Django 2.0.dev20170604010711 on 2017-06-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0002_auto_20170612_1121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='headermgr',
            table='dtb_header_mgr',
        ),
    ]
