# Generated by Django 2.0.dev20170604010711 on 2017-06-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0006_auto_20170613_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category_CategoryParent', to='demandware.Category', to_field='category_id'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_id', 'category_parent')},
        ),
    ]
