# Generated by Django 2.0.dev20170604010711 on 2017-06-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0008_auto_20170613_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category_CategoryParent', to='demandware.Category'),
        ),
    ]
