# Generated by Django 2.0.dev20170604010711 on 2017-06-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0011_auto_20170621_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_all_color_hexa_code',
            new_name='product_all_color',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_all_color_name',
            new_name='product_commentary',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='product_commentary_description',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='product_commentary_image',
        ),
    ]
