# Generated by Django 2.0.dev20170604010711 on 2017-06-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0012_auto_20170622_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color_hexa_code',
        ),
    ]
