# Generated by Django 2.0.dev20170604010711 on 2017-06-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0013_remove_variant_color_hexa_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymeta',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productmeta',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='relatedproduct',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='relatedproduct',
            old_name='related_product',
            new_name='related_product_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='categorymeta',
            unique_together={('category_id', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product_id', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='productmeta',
            unique_together={('product_id', 'key')},
        ),
    ]
