# Generated by Django 2.0.dev20170604010711 on 2017-06-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0015_auto_20170622_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='model_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
