# Generated by Django 2.0.dev20170604010711 on 2017-09-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0018_auto_20170907_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='en', max_length=100)),
                ('main_image', models.CharField(default='', max_length=255)),
                ('functions', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('display_name', models.CharField(default='', max_length=255)),
                ('product_all_size_info', models.TextField(null=True)),
                ('product_all_color', models.TextField(null=True)),
                ('product_commentary_image_title', models.CharField(max_length=255, null=True)),
                ('product_commentary', models.TextField(null=True)),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProductMaster_Extra_ProductMaster', to='demandware.ProductMaster', to_field='product_id')),
            ],
            options={
                'db_table': 'dtb_product_master_extra',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productmaster_extra',
            unique_together={('product_id', 'country')},
        ),
    ]
