# Generated by Django 2.0.dev20170604010711 on 2017-09-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0019_auto_20170911_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name_cn',
            new_name='category_name_en',
        ),
    ]
