# Generated by Django 2.0.dev20170604010711 on 2017-09-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0020_auto_20170920_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=100)),
                ('category_name', models.CharField(default='', max_length=255)),
                ('category_id', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category_Extra_Category', to='demandware.Category', to_field='category_id')),
            ],
            options={
                'db_table': 'dtb_category_extra',
            },
        ),
        migrations.AlterUniqueTogether(
            name='category_extra',
            unique_together={('category_id', 'language')},
        ),
    ]
