# Generated by Django 2.0.dev20170604010711 on 2017-09-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0022_category_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaster_extra',
            unique_together=set(),
        ),
    ]
