# Generated by Django 2.0.dev20170604010711 on 2017-09-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandware', '0023_auto_20170928_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaster_extra',
            unique_together={('product_id', 'country')},
        ),
    ]
